apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  project: argo-project-dev 
  source:
    repoURL: 'https://github.com/argoproj/argo-helm.git'
    targetRevision: 2.0.3
    helm:
      valueFiles:
        - https://github.com/JoaoRufino/helm-repo/raw/artidis/argo-workflows/values.yaml
    path: charts/argo-cd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

