## ArgoCD configuration
## Ref: https://github.com/argoproj/argo-cd
##
##
# Need to move some of these values to templates
argo-cd:
  installCRDs: false
  dex:
    enabled: false
  server:
    ingress:
      enabled: true
      hosts: 
        - argocd.192.168.49.2.nip.io
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm

    additionalProjects: 
    - name: argo
      namespace: argo
      additionalLabels: {}
      additionalAnnotations: {}
      description: Argos Related Applications
      #TODO: TESTING PURPOSES ONLY
      sourceRepos:
      - '*'
      destinations:
      - namespace: argo
        server: https://kubernetes.default.svc
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      orphanedResources:
        warn: false
    additionalApplications: 
      - name: root 
        namespace: argo
        destination:
          namespace: argo
          server: https://kubernetes.default.svc
        project: argo
        source:
          path: apps 
          repoURL: https://github.com/JoaoRufino/argocd.git
          targetRevision: HEAD
          helm:
            valueFiles:
            - values.yaml
        syncPolicy:
          syncOptions:
          - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true
  repoServer:
    image:
      repository: niplodim/argocd
      tag: v1 
    volumes:
      - name: sops-gpg-key
        secret:
          secretName: sops-gpg-key
    #gpg --export-secret-keys --armor "${SOPS_PGP_FP}" | kubectl create secret generic sops-gpg-key --namespace=argo --from-file=gpg.asc=/dev/stdin
    volumeMounts:
      - name: sops-gpg-key
        mountPath: /home/argocd/gpg/
        readOnly: true
