apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
spec:
  project: default
  source:
    repoURL: 'https://github.com/argoproj/argo-helm.git'
    targetRevision: 0.2.5
    helm:
      valueFiles:
        - https://github.com/JoaoRufino/helm-repo/raw/artidis/argo-workflows/values.yaml
    path: charts/argo-workflows
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

